SHOW TABLES;
CREATE TABLE grade (
	idx INT NOT NULL AUTO_INCREMENT,
	grade CHAR(5) DEFAULT '일반회원',
	maxborrowNum INT NOT NULL,
	PRIMARY KEY(idx)
);
DROP TABLE grade;
DESC grade;
SELECT * FROM grade;
INSERT INTO grade VALUES(DEFAULT,'관리자', 100000);
INSERT INTO grade VALUES(DEFAULT,'운영자', 100000);
INSERT INTO grade VALUES(DEFAULT,'일반회원', 5);
INSERT INTO grade VALUES(DEFAULT,'우수회원', 10);

CREATE TABLE 